environment:
  LANG: en_US.utf-8
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    CLONE_FOLDER: /home/appveyor/projects/PowerShell-Lib
    PS_BIN: pwsh
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CLONE_FOLDER: c:\projects\PowerShell-Lib
    PS_BIN: powershell
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CLONE_FOLDER: c:\projects\PowerShell-Lib
    PS_BIN: pwsh

version: '{build}'

clone_folder: $(CLONE_FOLDER)

install:
  - ps: .$env:PS_BIN -File (Join-Path -Path $env:CLONE_FOLDER -ChildPath "appveyor" | Join-Path -ChildPath "install.ps1")

build_script:
  - ps: .$env:PS_BIN -File (Join-Path -Path $env:CLONE_FOLDER -ChildPath "appveyor" | Join-Path -ChildPath "build_script.ps1")

test_script:
  - ps: .$env:PS_BIN -File (Join-Path -Path $env:CLONE_FOLDER -ChildPath "appveyor" | Join-Path -ChildPath "test_script.ps1")

on_finish:
  - ps: .$env:PS_BIN -File (Join-Path -Path $env:CLONE_FOLDER -ChildPath "appveyor" | Join-Path -ChildPath "on_finish.ps1")
